In [3]:
<div class="burk">
!pip install numpy</div><i class="fa fa-lightbulb-o "></i>

In [8]:
import numpy as np

In [9]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [10]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://www.scipy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide a

In [11]:
np.arange.__doc__

'arange([start,] stop[, step,], dtype=None, *, like=None)\n\n    Return evenly spaced values within a given interval.\n\n    Values are generated within the half-open interval ``[start, stop)``\n    (in other words, the interval including `start` but excluding `stop`).\n    For integer arguments the function is equivalent to the Python built-in\n    `range` function, but returns an ndarray rather than a list.\n\n    When using a non-integer step, such as 0.1, the results will often not\n    be consistent.  It is better to use `numpy.linspace` for these cases.\n\n    Parameters\n    ----------\n    start : integer or real, optional\n        Start of interval.  The interval includes this value.  The default\n        start value is 0.\n    stop : integer or real\n        End of interval.  The interval does not include this value, except\n        in some cases where `step` is not an integer and floating point\n        round-off affects the length of `out`.\n    step : integer or real, opti

In [12]:
import time

In [16]:
time.time()

1680208064.5006816

In [17]:
start = time.time()

In [22]:
size = 10000000

l1= range(size)
l2= range(size)

a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x+y) for x, y in zip(l1,l2)]
print("python list took: ", (time.time() - start) * 1000)

start = time.time()
result = a1 + a2
print("numpy took: ", (time.time() - start) * 1000)

python list took:  1443.030595779419
numpy took:  154.8025608062744


In [23]:
import sys

In [24]:
sys.getsizeof(5)

28

In [25]:
sys.getsizeof(5555)

28

In [26]:
sys.getsizeof("a")

50

In [27]:
sys.getsizeof("aaaaaa")

55

In [28]:
l = range(1000)

print(sys.getsizeof(5))
print(sys.getsizeof(5) *len(l))


a=np.arange(1000)

print(a.itemsize)
print(a.itemsize * a.size)

28
28000
4
4000


In [29]:
a = [1,2,3,4]
b = [4,3,2,1]


In [30]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i] * b[i])
    
ab

[4, 6, 6, 4]

In [31]:
a1=np.array(a)
a2=np.array(b)

In [32]:
a1 * a2

array([4, 6, 6, 4])

In [33]:
a1 / a2

array([0.25      , 0.66666667, 1.5       , 4.        ])

In [34]:
a1 + a2

array([5, 5, 5, 5])

In [35]:
a1 - a2

array([-3, -1,  1,  3])

# 1 array

In [37]:
mylist = [1,2,3]
mylist

[1, 2, 3]

In [38]:
np.array(mylist)

array([1, 2, 3])

In [39]:
np.array([1,2,3])

array([1, 2, 3])

In [41]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [42]:
mylist2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [43]:
mylist2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [44]:
myarray = np.array(mylist2)

In [45]:
myarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# 2 shape & reshape

In [46]:
myarray.shape

(4, 3)

In [47]:
myarray.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
myarray.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [49]:
myarray.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [52]:
myarray.reshape(12).reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
myarray.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
myarray.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 3 ndim

In [68]:
mylist = list(range(0,12))

In [70]:
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [71]:
myarray = np.array(mylist)

In [72]:
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
myarray.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
myarray = np.array(mylist, ndmin=4)

In [77]:
myarray

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]]])

# 4 dtype & astype

In [78]:
my_int = np.array([1,2,3])
my_int

array([1, 2, 3])

In [79]:
my_int.dtype

dtype('int32')

In [80]:
my_float = np.array([1. ,2.2,3,6,5])
my_float

array([1. , 2.2, 3. , 6. , 5. ])

In [81]:
my_float.dtype

dtype('float64')

In [82]:
my_string = np.array([1.,2.2,3,6,5, "a"])
my_string

array(['1.0', '2.2', '3', '6', '5', 'a'], dtype='<U32')

In [83]:
my_string.dtype

dtype('<U32')

In [84]:
x = np.array([1,2], dtype=np.float64)
print(x)
print(x.dtype)

[1. 2.]
float64


In [85]:
x = np.array([1,2], dtype=np.float32)
print(x)
print(x.dtype)

[1. 2.]
float32


In [86]:
newx = x.astype("i")

print(newx)
print(newx.dtype)

[1 2]
int32


In [89]:
arr = np.array([0,1,2])
newarr= arr.astype(bool)

print(newarr)
print(newarr.dtype)      

[False  True  True]
bool
